name = input("what is your name: ")
last_name = input("what is your last name: ")
age = input("what is your age: ")
country = input("where are u from: ")
fav_car = input("what is ur favorite car: ")
color = input("what is your favorite color: ")
fav_number = input("what is your favorite number: ")

print("my name is", name, last_name, ", i am", age, "years old", ", i live in", country, ", my favorite car is", fav_car, ", my favorite color is", color, "and my favorite number is", fav_number)



number1 = int(input("enter number: "))
number2 = int(input("enter number: "))
number3 = int(input("enter number: "))

print(number1 - number2)
print(number2 - number3)
print(number3 - number1)
print(number1 / number2)
print(number2 / number3)
print(number3 / number1)
print(number2 * number1)
print(number1 * number3)
print(number3 * number2)
print(number1 + number3)
print(number3 + number2)
print(number1 + number2)
print(number3 // number1)
print(number1 // number2)
print(number2 // number3)

person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
person1 = input("Person 1: ")
person2 = input("Person 2: ")
